# Generated by Django 5.2.4 on 2025-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('courts', models.IntegerField()),
                ('maps', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
                'ordering': ['name'],
                'default_related_name': 'facilities',
                'indexes': [models.Index(fields=['is_active'], name='facility_is_active_idx'), models.Index(fields=['is_deleted'], name='facility_is_deleted_idx'), models.Index(fields=['name'], name='facility_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_facility_name_not_empty'), models.CheckConstraint(condition=models.Q(('address', ''), _negated=True), name='ck_facility_address_not_empty'), models.CheckConstraint(condition=models.Q(('courts__gte', 0)), name='ck_facility_courts_non_negative'), models.UniqueConstraint(fields=('name', 'address'), name='uq_facility_name_address')],
            },
        ),
    ]
