# Generated by Django 5.2.4 on 2025-08-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_categories', to='categories.category')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_categories', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_categories',
                'indexes': [models.Index(fields=['tournament', 'category'], name='tournament__tournam_a1dab0_idx'), models.Index(fields=['category'], name='tournament__categor_bea9a8_idx')],
                'unique_together': {('tournament', 'category')},
            },
        ),
    ]
