# Generated by Django 5.2.4 on 2025-08-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tournament_categories', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournamentcategory',
            name='tournament__tournam_a1dab0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='tournament',
            field=models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_categories', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='tournamentcategory',
            index=models.Index(fields=['tournament', 'name'], name='tournament__tournam_4bc40c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentcategory',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_name'),
        ),
    ]
