# Generated by Django 5.2.4 on 2025-08-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tournament_categories', '0002_remove_tournamentcategory_tournament__tournam_a1dab0_idx_and_more'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentcategory',
            options={'verbose_name': 'Tournament Category', 'verbose_name_plural': 'Tournament Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='tournamentcategory',
            name='uniq_tournament_name',
        ),
        migrations.RemoveIndex(
            model_name='tournamentcategory',
            name='tournament__categor_bea9a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournamentcategory',
            name='tournament__tournam_4bc40c_idx',
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='comment',
            field=models.TextField(blank=True, db_column='comment', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AddConstraint(
            model_name='tournamentcategory',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_name_per_tournament'),
        ),
    ]
