# Generated by Django 5.2.4 on 2025-08-29 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tournament_categories', '0003_alter_tournamentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcategory',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0, max_digits=10),
        ),
    ]
