# Generated by Django 5.2.4 on 2025-08-12 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text='El nombre debe tener minimo 5 catacteres', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_start', models.DateTimeField(db_column='date_start')),
                ('date_end', models.DateTimeField(db_column='date_end')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='facilities.facility')),
            ],
        ),
    ]
