# Generated by Django 5.2.4 on 2025-09-16 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text='El nombre debe tener minimo 5 catacteres', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_start', models.DateTimeField(db_column='date_start')),
                ('date_end', models.DateTimeField(db_column='date_end')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(db_column='facility_id', on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'tournaments',
                'ordering': ['-date_start', '-id'],
                'default_related_name': 'tournaments',
                'indexes': [models.Index(fields=['facility'], name='tourn_facility_idx'), models.Index(fields=['is_active'], name='tourn_is_active_idx'), models.Index(fields=['date_start'], name='tourn_date_start_idx'), models.Index(fields=['date_end'], name='tourn_date_end_idx'), models.Index(fields=['facility', 'is_active'], name='tourn_facility_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_tournament_name_not_empty'), models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='ck_tournament_dates_valid')],
            },
        ),
    ]
