# Generated by Django 5.2.4 on 2025-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('cod', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
                'default_related_name': 'cities',
                'indexes': [models.Index(fields=['is_active'], name='city_is_active_idx'), models.Index(fields=['is_deleted'], name='city_is_deleted_idx'), models.Index(fields=['name'], name='city_name_idx'), models.Index(fields=['cod'], name='city_cod_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_city_name_not_empty'), models.CheckConstraint(condition=models.Q(('cod', ''), _negated=True), name='ck_city_cod_not_empty'), models.UniqueConstraint(fields=('cod',), name='uq_city_cod')],
            },
        ),
    ]
