# Generated by Django 5.2.4 on 2025-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
                'default_related_name': 'categories',
                'indexes': [models.Index(fields=['is_active'], name='cat_is_active_idx'), models.Index(fields=['name'], name='cat_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uq_category_name')],
            },
        ),
    ]
