# Generated by Django 5.2.4 on 2025-09-01 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_alter_player_category'),
        ('tournament_categories', '0004_alter_tournamentcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_as_partner', to='players.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_as_player', to='players.player')),
                ('tournament_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament_categories.tournamentcategory')),
            ],
            options={
                'db_table': 'registrations_registration',
                'indexes': [models.Index(fields=['tournament_category'], name='registratio_tournam_d31b3d_idx'), models.Index(fields=['player'], name='registratio_player__549967_idx'), models.Index(fields=['partner'], name='registratio_partner_f74e7b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('player__lt', models.F('partner'))), name='registrations_player_lt_partner'), models.UniqueConstraint(fields=('tournament_category', 'player', 'partner'), name='uq_registration_pair_in_category')],
            },
        ),
    ]
