# Generated by Django 5.2.4 on 2025-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
                'default_related_name': 'roles',
                'indexes': [models.Index(fields=['is_active'], name='role_is_active_idx'), models.Index(fields=['is_deleted'], name='role_is_deleted_idx'), models.Index(fields=['name'], name='role_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_role_name_not_empty'), models.UniqueConstraint(fields=('name',), name='uq_role_name')],
            },
        ),
    ]
