# Generated by Django 5.2.4 on 2025-09-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, choices=[('REVES', 'Reves'), ('DRIVE', 'Drive')], max_length=8, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='categories.category')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
                'ordering': ['nick_name'],
                'default_related_name': 'players',
            },
        ),
    ]
