# Generated by Django 5.2.4 on 2025-09-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_active'], name='player_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['nick_name'], name='player_nick_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('nick_name', ''), _negated=True), name='ck_player_nick_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 0), ('points__isnull', True), _connector='OR'), name='ck_player_points_ge0'),
        ),
    ]
