# Generated by Django 5.2.4 on 2025-08-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='categories.category'),
        ),
    ]
